### PR TITLE
fix #1747

### LINKED ISSUE #1747: Error when searching unreferenced assets in empty groups.
### Describe the bug

UTMT gives an error and crashes when searching unreferenced assets in empty groups.
I know, why should I search unreferenced assets in empty groups? Well, I was just looking for bugs.
ultim1
ultim2
ultim3
The game was Undertale.

### Reproducing steps

1. Open UndertaleModTool
2. Open Undertale's data.win
3. Go to Find
4. Click Find unreferenced assets
5. Select the empty group
6. Click search
7. Error

### Setup Details

1. UndertaleModTool version: Bleeding Edge 6056f06
2. OS: Windows 11 Pro

### PR DESCRIPTION
**Pull request by zivmaor**
## Description

Fix #1747 by not running the ForEach loop over the assets if there are no assets to check.
### Caveats

None that I could find.
### Notes

The diff seems long but ignoring whitespaces/indentation only 7 lines were changed.

### CODE REVIEW

**Review by colinator27 — APPROVED** [review]

File: UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs [hunk 1]
```diff
@@ -1498,39 +1498,42 @@ public static async Task<Dictionary<string, List<object>>> GetUnreferencedObject
                 mainWindow.SetProgressBar(null, "Assets", 0, assets.Count);
                 mainWindow.StartProgressBarUpdater();
 
-                var assetsPart = Partitioner.Create(0, assets.Count);
-
                 List<Dictionary<string, List<object>>> dicts = new();
 
-                await Task.Run(() =>
+                if (assets.Count  != 0) // A Partitioner can't be created on an empty list.
```
Comment (Miepee) [inline UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs:1503]: please fix the whitespace here.
I also personally prefer `> 0` but thats semantics.

Comment (zivmaor) [reply UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs]: Done. I agree that `> 0` looks better.
