### PR TITLE
Increase flexibility in last shader length

### LINKED ISSUE #391: Test project with passthrough shader compiled for vita doesn't open in UndertaleModTool
This game throws an exception regarding the length of shaders. If this exception is ignored, it can resave the file, with a one byte difference. It is a very odd thing, and would like some help investigating it. 

[game.zip](https://github.com/krzys-h/UndertaleModTool/files/6160075/game.zip)

### PR DESCRIPTION
**Pull request by Jacky720**
## Description
Per comment on #391, the last piece of raw shader data can sometimes be misaligned with the padding at the end of the chunk. This PR adds flexibility to the raw shader length checks to permit a greater (padded) size than expected when the raw shader data being parsed is the last one in the shader. Closes #391.

### Caveats
None. Any external use of UndertaleRawShaderData.ReadData should function the same, as the isLast parameter was given a default value.

### Notes
N/A

### CODE REVIEW

File: UndertaleModLib/Models/UndertaleShader.cs [hunk 1]
```diff
@@ -528,10 +528,20 @@ public void WriteData(UndertaleWriter writer)
...
         {
-            if (_Length != 0 && _Length != length)
-                throw new UndertaleSerializationException("Failed to compute length of shader data");
+            if (_Length != 0) // _Length is the "expected" length here
+            {
+                if (_Length > length)
+                    throw new UndertaleSerializationException("Failed to compute length of shader data: instructed to read less data than expected.");
+                else if (_Length < length)
+                {
+                    if (isLast) // Normal for the last element due to chunk padding, just trust the system
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleShader.cs:539]: Is there no way to detect how much padding we should have? would be nicer.

Comment (Jacky720) [reply UndertaleModLib/Models/UndertaleShader.cs:539]: I haven't done extensive testing with this. I think the maximum padding would be 15 bytes but I don't know everything about padding and kind of figured we try to work with whatever padding the file comes with.

Comment (Miepee) [reply UndertaleModLib/Models/UndertaleShader.cs:539]: Well, if you know how things are aligned on, you can determine that by checking the current reader position.
i.e. if things are always 16-aligned, and your current position is on 30, you'd have 2 padding. If your position is on 20, you'd have 12 padding etc.

**Review by Miepee — APPROVED** [review]

File: UndertaleModLib/Models/UndertaleShader.cs [hunk 2]
```diff
@@ -528,10 +528,21 @@ public void WriteData(UndertaleWriter writer)
...
+                if (_Length > length)
+                    throw new UndertaleSerializationException("Failed to compute length of shader data: instructed to read less data than expected.");
+                else if (_Length < length)
+                {
+                    if (isLast && ((reader.AbsPosition + length) % 16 == 0)) // Normal for the last element due to chunk padding, just trust the system
+                        length = (int)_Length;
+                    else
+                        throw new UndertaleSerializationException("Failed to compute length of shader data: instructed to read more data than expected." +
+                            (isLast ? " Shader data was the last in the shader, but given length was incorrectly padded." : ""));
+                }
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleShader.cs:544]: just noticed: can you make this slightly easier to read by using curly brackets please?

**Review by colinator27 — APPROVED** [review]
There may be cases where the "isLast" check isn't actually correct, but considering this should only affect cases where an exception was originally thrown, this should be fine.
