### PR TITLE
Compiler struct support

### LINKED ISSUE #1084: GameMaker struct type compiler support
### Which component should be improved?

Compiler

### Describe your feature suggestion in more detail

image

I checked out that UMT decompiles struct very well, but it can't be compiled back.

Implementation-wise, I think there are two ways (not exclusive to each other) to handle structs. One way is to modify parser: [ParseBlock()](https://github.com/krzys-h/UndertaleModTool/blob/e2b8022c72d44c3af83078d7e168f958cd7007a2/UndertaleModLib/Compiler/Parser.cs#L540) should detect structs with `:` token. The other way is to modify lexer: opening/closing braces should be lexed as `OpenBlock`/`CloseBlock` or `OpenStruct`/`CloseStruct`(to be added) based on the context and then be parsed separately from blocks.

I'm not familiar with GameMaker nor with Compiler stuff so I might be wrong.

### PR DESCRIPTION
**Pull request by CST1229**
Resolves #1084

## Description
Adds support for GMS2.3+ structs in the compiler, cherrypicked from [UndertaleModTool Community Edition](https://github.com/XDOneDude/UndertaleModToolCE/) with some additional minor changes.

https://github.com/krzys-h/UndertaleModTool/assets/68464103/7ac27e6d-29be-47fa-a8d7-e9153e586fea

Also fixes a bug where an empty struct definition would cause all assignments after to also be struct-styled, causing syntax errors when recompiling.
a = {}; b: 123

### Caveats
`___struct___` can no longer be used at the start of a function definition name, as parts of the compiler and decompiler assume that the `___struct___` prefix means a struct.

### Notes
I've only tested this on one GMS2022.9 game (Pizza Tower), but it seems to work there. You may want to squash this PR if you don't like some of my ridiculous commit names. (Also, I'm not super experienced with C# or this project's code style so there probably are some things that need  to be looked at.)

### CODE REVIEW

File: UndertaleModLib/Compiler/Compiler.cs [hunk 1]
```diff
@@ -54,6 +56,22 @@ public void OnSuccessfulFinish()
                 {
                     foreach (KeyValuePair<string, string> v in GlobalVars)
                         Data?.Variables?.EnsureDefined(v.Key, UndertaleInstruction.InstanceType.Global, false, Data.Strings, Data);
+                    if (Data != null) {
```
Comment (Miepee) [inline UndertaleModLib/Compiler/Compiler.cs:59]: Use `is not null` please. Not just here, but everywhere

File: UndertaleModLib/Compiler/Compiler.cs [hunk 2]
```diff
@@ -54,6 +56,22 @@ public void OnSuccessfulFinish()
...
+                            UndertaleScript scriptObj = Data.Scripts.ByName(scriptName);
+                            if (scriptObj != null) Data.Scripts.Remove(scriptObj);
+                            UndertaleCode codeObj = Data.Code.ByName(scriptName);
+                            if (codeObj != null) {
+                                Data.Code.Remove(codeObj);
+                                OriginalCode.ChildEntries.Remove(codeObj);
+                            }
+                            UndertaleFunction functionObj = Data.Functions.ByName(scriptName);
+                            if (functionObj != null) Data.Functions.Remove(functionObj);
+                            Data.KnownSubFunctions.Remove(name);
```
Comment (Miepee) [inline UndertaleModLib/Compiler/Compiler.cs:71]: This thing looks a bit weird. Can a scriptName be both in Data.Scripts and Data.Code ? To my knowledge assets have to have unique names.

File: UndertaleModLib/Compiler/Parser.cs [hunk 3]
```diff
@@ -668,6 +690,9 @@ private static Statement ParseFunction(CompileContext context)
                 {
                     expressionMode = false;
                     Statement s = remainingStageOne.Dequeue();
+                    if (s.Text.StartsWith("___struct___")) {
```
Comment (Miepee) [inline UndertaleModLib/Compiler/Parser.cs:693]: Is it possible for any real GM games out in the wild to have functions that start with `__struct__`? If not, you may wanna slap a todo onto this.

File: UndertaleModLib/Compiler/Parser.cs [hunk 4]
```diff
@@ -1553,6 +1579,132 @@ private static Statement ParseArrayLiteral(CompileContext context)
...
+                    varName = usableStructNames.Dequeue();
+                } else {
+                    // Create a new function
+                    int i = context.Data.Code.Count;
+                    do {
+                        varName = "___struct___" + context.OriginalCode.Name.Content +
+                            "__" + uuidCounter++.ToString();
+                        i++;
+                    } while (context.Data.KnownSubFunctions.ContainsKey(varName));
+                }
```
Comment (Miepee) [inline UndertaleModLib/Compiler/Parser.cs:1609]: can you format this to comfort to c# style?

**Review by Miepee — COMMENTED** [review]
i dont have any experience with that part of the codebase at all, so just a few cents

File: UndertaleModLib/Compiler/Compiler.cs (hunk 2 above)
Comment (CST1229) [reply UndertaleModLib/Compiler/Compiler.cs:71]: Yes I think, each function definition is in both Scripts and Code (Data.Scripts.ByName and Data.Code.ByName both return those entries too):
image

File: UndertaleModLib/Compiler/Parser.cs (hunk 3 above)
Comment (CST1229) [reply UndertaleModLib/Compiler/Parser.cs:693]: GM does seem to let you compile functions that start with `___struct___`, so maybe (though unlikely).

File: UndertaleModLib/Compiler/Compiler.cs (hunk 1 above)
Comment (CST1229) [reply UndertaleModLib/Compiler/Compiler.cs]: done

File: UndertaleModLib/Compiler/Compiler.cs (hunk 2 above)
Comment (Miepee) [reply UndertaleModLib/Compiler/Compiler.cs]: huh, TIL.

**Comment by Miepee** [comment]
Also can you add fixes #1399 to the inital PR description please??

**Comment by CST1229** [comment]
> Also can you add fixes #1399 to the inital PR description please?

That issue seems more like it's about `struct.func()` calls, which this PR does not resolve.

File: UndertaleModLib/Compiler/Compiler.cs [hunk 5]
```diff
@@ -54,6 +56,27 @@ public void OnSuccessfulFinish()
...
+                                Data.Scripts.Remove(scriptObj);
+                            UndertaleCode codeObj = Data.Code.ByName(scriptName);
+                            if (codeObj is not null)
+                            {
+                                Data.Code.Remove(codeObj);
+                                OriginalCode.ChildEntries.Remove(codeObj);
+                            }
+                            UndertaleFunction functionObj = Data.Functions.ByName(scriptName);
+                            if (functionObj is not null)
+                                Data.Functions.Remove(functionObj);
```
Comment (VladiStep) [inline UndertaleModLib/Compiler/Compiler.cs:75]: Are these instances of `Data.X.Remove()` safe?

Comment (CST1229) [reply UndertaleModLib/Compiler/Compiler.cs:75]: Should be if you're just normally adding and removing struct definitions, as each struct definition gets its own script, the compiler currently won't let you create `___struct___` functions and I'm fairly sure code, script and function references are all passed by reference instead of ID. But I'm not sure.
(If we don't remove unused struct functions, then adding then removing a struct definition would cause an `Unable to find function` error when launching the game.)

File: UndertaleModLib/Compiler/Parser.cs [hunk 6]
```diff
@@ -439,8 +446,17 @@ public static Statement ParseTokens(CompileContext context, List<Lexer.Token> to
...
                 context.Enums.Clear();
+                context.FunctionsToObliterate.Clear();
+                uuidCounter = 0;
                 hasError = false;
 
+                usableStructNames.Clear();
+                foreach (UndertaleCode child in context.OriginalCode.ChildEntries)
+                {
+                    if (child.Name.Content.StartsWith("gml_Script____struct___"))
+                        usableStructNames.Enqueue(child.Name.Content["gml_Script_".Length..]);
```
Comment (colinator27) [inline UndertaleModLib/Compiler/Parser.cs:457]: Is this entirely exhaustive? Depending on case, structs may not start with this, i.e. if embedded inside an anonymous function (`anon` part comes first in those cases). Although, I'm unsure if anonymous functions are supported by this compiler right now anyway.

Comment (CST1229) [reply UndertaleModLib/Compiler/Parser.cs:457]: > Depending on case, structs may not start with this, i.e. if embedded inside an anonymous function (anon part comes first in those cases).

At least from my tests in GMS2022.9, that does not seem to be the case (although it might be different in earlier or later versions).
image


> Although, I'm unsure if anonymous functions are supported by this compiler right now anyway.

Sort of, but they don't work that well.
image
image

Comment (Miepee) [reply UndertaleModLib/Compiler/Parser.cs:457]: AFAIK there's an open issue somewhere about anonymous functions, to my understanding their status essentially boils down to "unsupported/not working"

File: UndertaleModLib/Compiler/AssemblyWriter.cs [hunk 7]
```diff
@@ -1332,7 +1375,10 @@ private static void AssembleExpression(CodeWriter cw, Parser.Statement e, Parser
                             });
                             cw.typeStack.Push(DataType.Variable);
                             cw.Emit(Opcode.Dup, DataType.Variable).Extra = 0;
-                            cw.Emit(Opcode.PushI, DataType.Int16).Value = (short)-1; // todo: -6 sometimes?
+                            if (isStructDef)
+                                cw.Emit(Opcode.PushI, DataType.Int16).Value = (short)-16;
+                            else
+                                cw.Emit(Opcode.PushI, DataType.Int16).Value = (short)-1; // todo: -6 sometimes?
```
Comment (Miepee) [inline UndertaleModLib/Compiler/AssemblyWriter.cs:1381]: can you capitalize TODO please?

Comment (Miepee) [reply UndertaleModLib/Compiler/AssemblyWriter.cs:1381]: oh whoops. i only saw it now in the diff

**Review by Miepee — APPROVED** [review]

File: UndertaleModLib/Compiler/Parser.cs (hunk 6 above)
Comment (colinator27) [reply UndertaleModLib/Compiler/Parser.cs:458]: OK so I further investigated this, and I found out that the code entries I saw were just anonymous functions declared inside of structs, which aren't themselves structs, so this check is fine!

**Review by colinator27 — APPROVED** [review]

**Comment by colinator27** [comment]
I temporarily ported these changes over to my new decompiler fork (almost verbatim), and it seems to work great there!
