### PR TITLE
Find references crash fix

### LINKED ISSUE #1946: UTMT crashes when using "Find unreferenced assets" on Undertale version 1.001
### Describe the bug

image
Seems to be because this data.win contains no LANG chunk.

### Reproducing steps

1. Open Undertale version 1.001 in UTMT
2. Try to use "Find unreferenced assets"
   * Make sure strings are selected.
4. The tool crashes.

### Setup Details

Tested on latest commit
data.win is Undertale version 1.001 (Windows, Steam), MD5: cd48b89b6ac6b2d3977f2f82726e5f12

### PR DESCRIPTION
**Pull request by zivmaor**
## Description

Fixes #1946 by only checking language for bytecode 16 and above games.
Based on https://github.com/UnderminersTeam/UndertaleModTool/wiki/Bytecode-version-differences.

Also adds error handling to all functions which use GetReferencesOfObject so if something similar happens again it won't cause the tool to crash.
### Notes

Replaces #1942.
Thanks to @maxiterr1 for bringing this to my attention.

### CODE REVIEW

**Review by maxiterr1 — APPROVED** [review]

File: UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs [hunk 1]
```diff
@@ -1577,6 +1590,9 @@ await Task.Run(() =>
                 funcReferences = null;
                 variReferences = null;
 
+                await mainWindow.StopProgressBarUpdater();
```
Comment (colinator27) [inline UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs:1593]: Super small nitpick, but we could probably use a `finally` block for this instead of duplicating the code. Otherwise, this looks good to me.

**Review by colinator27 — CHANGES_REQUESTED** [review]

File: UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs (hunk 1 above)
Comment (zivmaor) [reply UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs]: fixed

**Review by colinator27 — APPROVED** [review]

File: UndertaleModTool/Windows/FindReferencesTypesDialog/FindReferencesTypesDialog.xaml.cs [hunk 2]
```diff
@@ -173,9 +187,19 @@ private async void SearchButton_Click(object sender, RoutedEventArgs e)
...
-                FindReferencesResults dialog = new(data, results);
-                dialog.Show();
+                FindReferencesResults dialog = null;
+                try
+                {
+                    var results = await UndertaleResourceReferenceMethodsMap.GetUnreferencedObjects(data, typesDict);
+                    dialog = new(data, results);
+                    dialog.Show();
+                }
+                catch (Exception ex)
```
Comment (Miepee) [inline UndertaleModTool/Windows/FindReferencesTypesDialog/FindReferencesTypesDialog.xaml.cs:197]: can we somehow trickle the exception type further instead of just having a catchall?

**Review by Miepee — CHANGES_REQUESTED** [review]
blocking accidental merge, core dev can dismiss later if my above comment ends up being void

File: UndertaleModTool/Windows/FindReferencesTypesDialog/FindReferencesTypesDialog.xaml.cs (hunk 2 above)
Comment (zivmaor) [reply UndertaleModTool/Windows/FindReferencesTypesDialog/FindReferencesTypesDialog.xaml.cs:197]: As far as I understand we can't. This function is called directly from a button in XAML, so if we don't catch it here the application will crash.
This isn't a silent catchall and it should never be reached unless there is a bug. It is only here to stop the application from crashing if there is a bug, which is exactly what happens in #1946 and is way worse than the search just failing and showing an error message.

Comment (colinator27) [reply UndertaleModTool/Windows/FindReferencesTypesDialog/FindReferencesTypesDialog.xaml.cs:197]: Yeah, if it's just to prevent the entire application stability from being compromised, I'm OK with a catchall like this. Just need confirmation from @Miepee too

Comment (Miepee) [reply UndertaleModTool/Windows/FindReferencesTypesDialog/FindReferencesTypesDialog.xaml.cs:197]: well i meant more having a specicif exception type
so instead of `catch (Exception ex)` have `catch (InvalidAccessException ex)` or whatever exception type is used here.

Comment (colinator27) [reply UndertaleModTool/Windows/FindReferencesTypesDialog/FindReferencesTypesDialog.xaml.cs:197]: So in this case the crash was caused by a null pointer dereference (which also became an AggregateException), but since the point of it is to protect the user in the future, regardless of whatever bugs get introduced in the search process, I think plain Exception is probably the best. It's not like there's documented behavior for a bug we're not sure exists yet.

Comment (Miepee) [reply UndertaleModTool/Windows/FindReferencesTypesDialog/FindReferencesTypesDialog.xaml.cs:197]: eh, sure

**Review by Miepee — APPROVED** [review]
