### PR TITLE
UA: Add rough check for CodeLocals' removal from FUNC in 2024.8

### LINKED ISSUE #1928: Unable to read UFO 50 after 09/26/2024 update (v1.1.4)
### Describe the bug

Cannot open UFO 50 after patch: https://steamdb.info/patchnotes/15828959/

Screenshot 2024-09-26 192657

### Reproducing steps

1. Open UTMT
2. Attempt to open UFO 50

### Setup Details

I tried this with v6.0 stable, v6.1 bleeding edge, and underanalyzer branch artifact. All three provide various errors. The pictured error is from underanalyzer, whereas the other builds gave the usual `VARI` error.

### PR DESCRIPTION
**Pull request by Dobby233Liu**
## Description
As @colinator27 [noted](https://discord.com/channels/566861759210586112/568950566122946580/1271280990370664469) around the time of GM 2024.8(00) Beta's release, this GM version removes the CodeLocals list from the FUNC chunk. This PR adds logic to detect this, and makes builtin scripts aware of this.

Might fix #1928.

For contributors: feel free to continue this yourself if it's stuck in limbo or something.

### Caveats
* HEAVILY UNTESTED, the disassembler didn't get touched a lot. I only checked whether (de)serialization works as expected.
* Variable names are no longer highlighted in the code editor.

### Notes
Data.CodeLocals is now null if the bytecode version doesn't support it, it must be created manually if needed.

### CODE REVIEW

**Comment by Dobby233Liu** [comment]
Doesn't look too wrong so bug catching can take place. No clue what to do with the disassembler's message

**Comment by Dobby233Liu** [comment]
Amazing UX GitHub, I'm trying again. Might fix #1928.

**Comment by JeodC** [comment]
I am unable to use the search function when using this artifact fyi, but it *does* load 2024.8 data for reading and some editing. It seems to have a chance to somehow corrupt gml scripts, from time to time when I make a modification and leave a script, I'll try to come back to it and get that giant wall of greentext.

**Comment by LukeWarnut** [comment]
Can confirm that it does fix https://github.com/UnderminersTeam/UndertaleModTool/issues/1928

File: UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs [hunk 1]
```diff
@@ -624,7 +626,7 @@ IEnumerable<object[]> GetExtnFunctions()
                             if (objSrc is not UndertaleString obj)
                                 return null;
 
-                            var codeLocals = data.CodeLocals.Where(x => x.Name == obj || x.Locals.Any(l => l.Name == obj));
+                            var codeLocals = data.CodeLocals?.Where(x => x.Name == obj || x.Locals.Any(l => l.Name == obj));
```
Comment (zivmaor) [inline UndertaleModTool/Windows/FindReferencesTypesDialog/UndertaleResourceReferenceMethodsMap.cs:629]:
```suggestion
                            var codeLocals = data.CodeLocals.Where(x => x.Name == obj || x.Locals.Any(l => l.Name == obj));
```
Please revert this change. If something goes wrong the error shouldn't  just be swallowed here, especially after #1947 fixes the related error handling.

**Comment by JeodC** [comment]
[NewTextureRepacker.zip](https://github.com/user-attachments/files/17935901/NewTextureRepacker.zip)

I modified the NewTextureRepacker script to be a form instead of a messagebox. This is useful since it contains user configurable items that the user may wish to change on a per-game basis.

image

**Comment by JeodC** [comment]
FYI I am using this build and as of `2024.11` there is a SHDR error on data.win load as seen in #1996

**Comment by Dobby233Liu** [comment]
Okay, while there's all sorts of weirdness brought by this, like the mildly inconvenient code editor UI situation (probably got to rely on Colin's work here anyway as I have no idea how all that stuff works). Signs lead me to believe this is fair enough for initial implementation, and basically I'm done with it at this point (focus has moved on to #2013), so it's probably the right time (finally) to open this up for review so things can get moving faster.
